export const projects = [
  {
    title: 'MERN PROJECT',
    description: "The Workout Head App is a CRUD based web applications built by using MERN stack. It is a fully responsive web application which provides smooth and interactive experience to the users. This web app provides the features of Creating, Updating and Deleting the Workout Details to the users. The Frontend of this app is built by using ReactJs, and the Backend is built by using NodeJs and ExpressJs and all the workout details is stored in MongoDB Database.",
      image: '/images/Workout_img.png',
      tags: ['Node', 'Express', 'MongoDB', 'React'],
    source: 'https://flourishing-lokum-9ca12d.netlify.app/',
    visit: 'https://github.com/Kanish027/workoutheadfrontend',
    id: 0,
  },
  {
    title: 'Internship Project',
    description:"This is a full responsive Chattisgarhi YouTuber's website made during Internship, this website showcases their best content and accomplishment as a creator. It provides a  visually appealing  and user-friendly  platforms for fans. By utilizing HTML, CSS, and JavaScript, this website offers an engaging and interactive experience that aligns with their brands and enhances their online presence as a YouTuber.",
    image: '/images/Mor.png',
    tags: ['HTML', "CSS" ,'JavaScript'],
    source: 'https://mor-mitan-project.vercel.app/',
    visit: 'https://github.com/Kanish027/MorMitan-Project',
    id: 1,
  },
  {
    title: 'React Cart',
    description: "The React Cart is a web application built using the React JavaScript library. It allows users to create a virtual shopping cart to add and manage items they wish to purchase. The cart provides a smooth and interactive user experience, making it easy for customers to browse through products.",
      image: '/images/react-cart.png',
      tags: ['React', 'JavaScript'],
    source: 'https://shopping-cart-ten-blue.vercel.app',
    visit: 'https://github.com/Kanish027/react-cart',
    id: 0,
  },
  {
    title: 'Blog App',
    description: "The Blog App is a web applications built by using ReactJs. It is a fully responsive web application which provides smooth and interactive experience to the users. The Blog App provides the features of creating and deleting the blogs to the users. The data is stored in the json server which is deployed on render cloud.",
      image: '/images/BlogApp.png',
      tags: ['React','JavaScript'],
    source: 'https://blog-app-s4ex.vercel.app//',
    visit: 'https://github.com/Kanish027/Blog-App',
    id: 2,
  },
  {
    title: 'Ecommerce App',
    description: "The Ecommerce App is a complete dynamic web application built by using ReactJs, Strapi and Stripe. The Frontend is based on ReactJs which allows users to interact with various products and provides features such as filtering of products according to the categories, price and sort by. The Add To Cart features allows users to add their products in the cart. The ecommerce app is completely managed by using Strapi, which plays Backend's role in this application and it is deployed on Render Cloud. The Payment Gateway is built by using Stripe.",
    image: '/images/ecommerceApp.png',
    tags: ['React', 'Strapi', 'Stripe'],
    source: 'https://ecomexe.vercel.app/',
    visit: 'https://github.com/Kanish027/ecomexe',
    id: 3,
  },
  {
    title: 'Social Media UX/UI',
    description: "The Social Media User Interface is built by using ReactJs and MUI Library. This UI is fully responsive which provides smooth and interactive experience to the users.The UI comes with the features such as dark mode, color change when liked on post.",
    image: '/images/TEchy.png',
    tags: ['React', 'MUI-Library'],
    source: 'https://ux-ui-liard.vercel.app/',
    visit: 'https://github.com/Kanish027/ux-ui',
    id: 3,
  },
];

export const TimeLineData = [
  { year: 2017, text: 'Completed my SSC', },
  { year: 2019, text: 'Completed my HSC', },
  { year: 2023, text: 'Started Internship(Not completed, due to merger of the company with Technobase)', },
  { year: 2023, text: 'Completed BE in Information Technology', },
];